use orchestre_core::PianoParams;

use crate::filter::Svf;
use crate::util::{Rng, TAU, decay_coef, midi_to_hz, pan_gains};

const MAX_VOICES: usize = 24;
/// The lowest key without a damper.
const UNDAMPED: u8 = 91;
const HARMONICS: usize = 12;
/// The lowest partials also get a slightly detuned second "string".
const DOUBLED: usize = 3;
const PARTIALS: usize = HARMONICS + DOUBLED;

/// One sine partial, generated by a rotating phasor (no `sin` per sample),
/// with a two-stage (prompt + aftersound) decay like a real piano string.
#[derive(Clone, Copy, Default)]
struct Partial {
    c: f32,
    s: f32,
    cos_w: f32,
    sin_w: f32,
    fast: f32,
    slow: f32,
    fast_coef: f32,
    slow_coef: f32,
}

#[derive(Clone, Copy, Default)]
struct Voice {
    active: bool,
    note: u8,
    off_at: f64,
    age: u64,
    released: bool,
    partials: [Partial; PARTIALS],
    count: usize,
    release_coef: f32,
    damp: f32,
    attack: f32,
    attack_inc: f32,
    hammer: f32,
    hammer_coef: f32,
    hammer_filter: Svf,
    rng: Rng,
    pan: (f32, f32),
}

impl Voice {
    fn start(&mut self, p: &PianoParams, sr: f32, pitch: u8, vel: f32, off_at: f64, age: u64) {
        let f0 = midi_to_hz(pitch as f32);
        let rel = (pitch as f32 - 60.0) / 12.0;
        // Low strings ring much longer than high ones. Anchored on
        // Weinreich's measurement at E♭4: prompt sound ~8 dB/s (T60 7.5 s),
        // aftersound under a quarter of that rate (T60 30 s and more).
        let base_decay =
            (30.0 * (2.0f32).powf(-(pitch as f32 - 63.0) / 20.0)).clamp(1.5, 60.0) * p.decay;
        // Stiffer (more inharmonic) strings in the treble: the treble line
        // from Rigaud, David & Daudet (JASA 2013), B = exp(0.0926·m − 13.64).
        // (The bass rise varies too much between pianos to model here.)
        let inharm = (0.0926 * pitch as f32 - 13.64).exp();
        let tilt = 1.9 - p.brightness * 1.0 - vel * 0.5;
        let vel_gain = 0.15 + 0.85 * vel * vel;

        let mut count = 0;
        for i in 0..PARTIALS {
            let (n, detune) = if i < HARMONICS {
                (i + 1, 1.0)
            } else {
                // The second string of the unison, slightly sharp: all its
                // partials move together. Listeners prefer 1–2 cents
                // (Kirk 1959).
                (i - HARMONICS + 1, 1.0 + 0.0006 + p.detune * 0.003)
            };
            let nf = n as f32;
            let f = nf * f0 * (1.0 + inharm * nf * nf).sqrt() * detune;
            if f > sr * 0.45 {
                continue;
            }
            // Hammer strikes at ~1/8 of the string length, notching some partials.
            let strike = ((std::f32::consts::PI * nf * 0.12).sin()).abs() * 0.8 + 0.2;
            let mut amp = strike / nf.powf(tilt) * vel_gain;
            if i >= HARMONICS {
                amp *= 0.7;
            }
            let w = TAU * f / sr;
            let t = base_decay / (1.0 + 0.35 * (nf - 1.0));
            self.partials[count] = Partial {
                c: 1.0,
                s: 0.0,
                cos_w: w.cos(),
                sin_w: w.sin(),
                fast: amp * 0.65,
                slow: amp * 0.35,
                fast_coef: decay_coef(t * 0.25, sr),
                slow_coef: decay_coef(t, sr),
            };
            count += 1;
        }
        self.count = count;
        self.active = true;
        self.released = false;
        self.note = pitch;
        self.off_at = off_at;
        self.age = age;
        self.release_coef = decay_coef(0.25 + 0.3 * (-rel).max(0.0), sr);
        self.damp = 1.0;
        self.attack = 0.0;
        self.attack_inc = 1.0 / (0.002 * sr);
        self.hammer = p.hardness * vel * 0.6;
        self.hammer_coef = decay_coef(0.015 + 0.02 * (1.0 - p.hardness), sr);
        self.hammer_filter.reset();
        self.hammer_filter.set((f0 * 6.0).min(sr * 0.4), 0.3, sr);
        self.rng = Rng::new(0x5bd1_e995 ^ (age as u32).wrapping_mul(2_246_822_519));
        self.pan = pan_gains(rel / 4.0 * 0.6);
    }

    fn render(&mut self, gain: f32, l: &mut [f32], r: &mut [f32]) {
        let (gl, gr) = (self.pan.0 * gain, self.pan.1 * gain);
        let mut peak = 0.0f32;
        for i in 0..l.len() {
            let mut s = 0.0;
            for p in &mut self.partials[..self.count] {
                let c = p.c * p.cos_w - p.s * p.sin_w;
                p.s = p.c * p.sin_w + p.s * p.cos_w;
                p.c = c;
                p.fast *= p.fast_coef;
                p.slow *= p.slow_coef;
                s += p.s * (p.fast + p.slow);
            }
            if self.hammer > 1e-5 {
                s += self.hammer_filter.band(self.rng.noise()) * self.hammer;
                self.hammer *= self.hammer_coef;
            }
            if self.attack < 1.0 {
                self.attack = (self.attack + self.attack_inc).min(1.0);
            }
            if self.released {
                self.damp *= self.release_coef;
            }
            let out = s * self.attack * self.damp;
            peak = peak.max(out.abs());
            l[i] += out * gl;
            r[i] += out * gr;
        }
        // Renormalize phasors so rounding errors never grow.
        for p in &mut self.partials[..self.count] {
            let m = (p.c * p.c + p.s * p.s).sqrt();
            if m > 0.0 {
                p.c /= m;
                p.s /= m;
            }
        }
        let remaining: f32 = self.partials[..self.count]
            .iter()
            .map(|p| p.fast + p.slow)
            .sum::<f32>()
            * self.damp;
        if remaining < 1e-4 && self.hammer < 1e-4 && peak < 1e-4 {
            self.active = false;
        }
    }
}

pub struct PianoEngine {
    pub params: PianoParams,
    sr: f32,
    voices: [Voice; MAX_VOICES],
    counter: u64,
}

impl PianoEngine {
    pub fn new(params: PianoParams, sr: f32) -> Self {
        PianoEngine {
            params,
            sr,
            voices: [Voice::default(); MAX_VOICES],
            counter: 0,
        }
    }

    pub fn set_params(&mut self, params: PianoParams) {
        self.params = params;
    }

    pub fn note_on(&mut self, pitch: u8, vel: f32, off_at: f64) {
        self.counter += 1;
        // Re-striking the same key damps the previous strike.
        for v in self
            .voices
            .iter_mut()
            .filter(|v| v.active && v.note == pitch)
        {
            v.released = true;
            v.release_coef = decay_coef(0.05, self.sr);
        }
        let idx = self
            .voices
            .iter()
            .position(|v| !v.active)
            .or_else(|| {
                self.voices
                    .iter()
                    .enumerate()
                    .min_by_key(|(_, v)| v.age)
                    .map(|(i, _)| i)
            })
            .unwrap_or(0);
        let p = self.params;
        self.voices[idx].start(&p, self.sr, pitch, vel, off_at, self.counter);
    }

    fn release(v: &mut Voice, pedal: bool) {
        v.off_at = f64::INFINITY;
        // The top 18 keys (G6 and up) have no dampers.
        if !pedal && v.note < UNDAMPED {
            v.released = true;
        }
    }

    pub fn release_due(&mut self, tick: f64) {
        let pedal = self.params.pedal;
        for v in self
            .voices
            .iter_mut()
            .filter(|v| v.active && v.off_at <= tick)
        {
            Self::release(v, pedal);
        }
    }

    pub fn live_off(&mut self, pitch: u8) {
        let pedal = self.params.pedal;
        for v in self
            .voices
            .iter_mut()
            .filter(|v| v.active && v.note == pitch && v.off_at.is_infinite())
        {
            Self::release(v, pedal);
        }
    }

    pub fn all_off(&mut self) {
        for v in self.voices.iter_mut() {
            v.off_at = f64::INFINITY;
            v.released = true;
        }
    }

    pub fn render(&mut self, l: &mut [f32], r: &mut [f32]) {
        // Notes now sustain as long as measured: keep the attack as loud as before.
        let gain = self.params.gain * 0.36;
        for v in self.voices.iter_mut().filter(|v| v.active) {
            v.render(gain, l, r);
        }
    }
}
